# Generated by Django 6.0.5 on 2026-06-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToiletStatus',
            fields=[
                ('toilet_id', models.IntegerField(primary_key=True, serialize=False)),
                ('is_occupied', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
